package cis

import "strings"

func normalizeQuery(s string) string {
	hasCyrillic := false
	for _, r := range s {
		if (r >= 'А' && r <= 'Я') || (r >= 'а' && r <= 'я') || r == 'Ё' || r == 'ё' {
			hasCyrillic = true
			break
		}
	}
	if !hasCyrillic {
		return s
	}

	upper := strings.ToUpper(s)
	replacer := newSynonymReplacer()
	result := replacer.Replace(upper)
	return transliterateRemaining(result)
}

func transliterateRemaining(s string) string {
	var b strings.Builder
	for _, r := range s {
		switch r {
		case 'А':
			b.WriteRune('A')
		case 'Б':
			b.WriteRune('B')
		case 'В':
			b.WriteRune('V')
		case 'Г':
			b.WriteRune('G')
		case 'Д':
			b.WriteRune('D')
		case 'Е':
			b.WriteRune('E')
		case 'Ё':
			b.WriteString("YO")
		case 'Ж':
			b.WriteString("ZH")
		case 'З':
			b.WriteRune('Z')
		case 'И':
			b.WriteRune('I')
		case 'Й':
			b.WriteRune('Y')
		case 'К':
			b.WriteRune('K')
		case 'Л':
			b.WriteRune('L')
		case 'М':
			b.WriteRune('M')
		case 'Н':
			b.WriteRune('N')
		case 'О':
			b.WriteRune('O')
		case 'П':
			b.WriteRune('P')
		case 'Р':
			b.WriteRune('R')
		case 'С':
			b.WriteRune('S')
		case 'Т':
			b.WriteRune('T')
		case 'У':
			b.WriteRune('U')
		case 'Ф':
			b.WriteRune('F')
		case 'Х':
			b.WriteString("KH")
		case 'Ц':
			b.WriteString("TS")
		case 'Ч':
			b.WriteString("CH")
		case 'Ш':
			b.WriteString("SH")
		case 'Щ':
			b.WriteString("SHCH")
		case 'Ъ':
		case 'Ы':
			b.WriteRune('Y')
		case 'Ь':
		case 'Э':
			b.WriteRune('E')
		case 'Ю':
			b.WriteString("YU")
		case 'Я':
			b.WriteString("YA")
		default:
			b.WriteRune(r)
		}
	}
	return b.String()
}

func newSynonymReplacer() *strings.Replacer {
	var pairs []string

	for _, entry := range synonymEntries {
		pairs = append(pairs, entry.cyr, entry.lat)
	}

	return strings.NewReplacer(pairs...)
}

type synonymEntry struct {
	cyr string
	lat string
}

var synonymEntries = []synonymEntry{
	// Brands
	{"АКУРА", "ACURA"},
	{"ДАЙХАТСУ", "DAIHATSU"},
	{"ДАЙХАЦУ", "DAIHATSU"},
	{"ХОНДА", "HONDA"},
	{"ИНФИНИТИ", "INFINITI"},
	{"ИНФИНТИ", "INFINITI"},
	{"ИСУЗУ", "ISUZU"},
	{"ИЗУДЗУ", "ISUZU"},
	{"ЛЕКСУС", "LEXUS"},
	{"МАЗДА", "MAZDA"},
	{"МИЦУБИСИ", "MITSUBISHI"},
	{"МИТСУБИШИ", "MITSUBISHI"},
	{"МИЦУБИШИ", "MITSUBISHI"},
	{"МИТСУБИСИ", "MITSUBISHI"},
	{"НИССАН", "NISSAN"},
	{"НИСАН", "NISSAN"},
	{"СУБАРУ", "SUBARU"},
	{"СУЗУКИ", "SUZUKI"},
	{"СУДЗУКИ", "SUZUKI"},
	{"ТОЙОТА", "TOYOTA"},
	{"ТОЁТА", "TOYOTA"},
	{"ДЭВУ", "DAEWOO"},
	{"ДЕВУ", "DAEWOO"},
	{"ДАЕВУ", "DAEWOO"},
	{"ДЕУ", "DAEWOO"},
	{"ГЕНЕЗИС", "GENESIS"},
	{"ДЖЕНЕЗИС", "GENESIS"},
	{"ДЖЕНЕСИС", "GENESIS"},
	{"ХЁНДАЙ", "HYUNDAI"},
	{"ХЕНДАЙ", "HYUNDAI"},
	{"ХУНДАЙ", "HYUNDAI"},
	{"ХЮНДАЙ", "HYUNDAI"},
	{"ХЁНДЭ", "HYUNDAI"},
	{"ХЕНДЭ", "HYUNDAI"},
	{"КИА", "KIA"},
	{"ССАНГЙОНГ", "SSANGYONG"},
	{"САНГ ЙОНГ", "SSANGYONG"},
	{"САНЙОНГ", "SSANGYONG"},
	{"ССАНЙОНГ", "SSANGYONG"},
	{"ССАНГЪЁНГ", "SSANGYONG"},
	{"КГМ", "KGM"},
	{"АУДИ", "AUDI"},
	{"БМВ", "BMW"},
	{"БЭЭМВЭ", "BMW"},
	{"МЕРСЕДЕС БЕНЦ", "MERCEDES-BENZ"},
	{"МЕРСЕДЕС-БЕНЦ", "MERCEDES-BENZ"},
	{"МЕРСЕДЕС", "MERCEDES-BENZ"},
	{"МЕРС", "MERCEDES-BENZ"},
	{"ОПЕЛЬ", "OPEL"},
	{"ПОРШЕ", "PORSCHE"},
	{"ПОРШ", "PORSCHE"},
	{"СМАРТ", "SMART"},
	{"ФОЛЬКСВАГЕН", "VOLKSWAGEN"},
	{"ФОЛЬЦВАГЕН", "VOLKSWAGEN"},
	{"СИТРОЕН", "CITROEN"},
	{"СИТРОЁН", "CITROEN"},
	{"ДС", "DS"},
	{"ДИ ЭС", "DS"},
	{"ПЕЖО", "PEUGEOT"},
	{"РЕНО", "RENAULT"},
	{"АЛЬФА РОМЕО", "ALFA ROMEO"},
	{"АЛЬФАРОМЕО", "ALFA ROMEO"},
	{"ФЕРРАРИ", "FERRARI"},
	{"ФИАТ", "FIAT"},
	{"ЛАМБОРГИНИ", "LAMBORGHINI"},
	{"ЛАМБОРДЖИНИ", "LAMBORGHINI"},
	{"ЛЯНЧА", "LANCIA"},
	{"ЛАНЧИЯ", "LANCIA"},
	{"МАЗЕРАТИ", "MASERATI"},
	{"АСТОН МАРТИН", "ASTON MARTIN"},
	{"АСТОНМАРТИН", "ASTON MARTIN"},
	{"БЕНТЛИ", "BENTLEY"},
	{"ЯГУАР", "JAGUAR"},
	{"ЛЕНД РОВЕР", "LAND ROVER"},
	{"ЛЭНД РОВЕР", "LAND ROVER"},
	{"ЛАНД РОВЕР", "LAND ROVER"},
	{"МАКЛАРЕН", "MCLAREN"},
	{"МИНИ", "MINI"},
	{"РОЛЛС РОЙС", "ROLLS-ROYCE"},
	{"РОЛЛС-РОЙС", "ROLLS-ROYCE"},
	{"РОЛС РОЙС", "ROLLS-ROYCE"},
	{"БЬЮИК", "BUICK"},
	{"КАДИЛЛАК", "CADILLAC"},
	{"КАДИЛАК", "CADILLAC"},
	{"ШЕВРОЛЕ", "CHEVROLET"},
	{"ШЕВРОЛЕТ", "CHEVROLET"},
	{"КРАЙСЛЕР", "CHRYSLER"},
	{"ДОДЖ", "DODGE"},
	{"ФОРД", "FORD"},
	{"ДЖИЭМСИ", "GMC"},
	{"ХАММЕР", "HUMMER"},
	{"ДЖИП", "JEEP"},
	{"ЛИНКОЛЬН", "LINCOLN"},
	{"ТЕСЛА", "TESLA"},
	{"СААБ", "SAAB"},
	{"ВОЛЬВО", "VOLVO"},
	{"ШКОДА", "SKODA"},
	{"СЕАТ", "SEAT"},
	{"ДАЧИЯ", "DACIA"},
	{"ДАЦИЯ", "DACIA"},
	{"АВАТР", "AVATR"},
	{"АВАТАР", "AVATR"},
	{"БАИК", "BAIC"},
	{"БАИС", "BAIC"},
	{"БЕЙК", "BAIC"},
	{"БЕЛДЖИ", "BELGEE"},
	{"БЕЛГИ", "BELGEE"},
	{"БЕЛДЖИИ", "BELGEE"},
	{"БЕСТЮН", "BESTUNE"},
	{"БЕСТУН", "BESTUNE"},
	{"БИД", "BYD"},
	{"БЮИД", "BYD"},
	{"БИУАЙДИ", "BYD"},
	{"ЧАНГАН", "CHANGAN"},
	{"ЧАНАНЬ", "CHANGAN"},
	{"ШАНГАН", "CHANGAN"},
	{"ЧЕРИ", "CHERY"},
	{"ЧЕРРИ", "CHERY"},
	{"ЧЭРИ", "CHERY"},
	{"ДИПАЛ", "DEEPAL"},
	{"ДИПЭЛ", "DEEPAL"},
	{"ДОНГФЕНГ", "DONGFENG"},
	{"ДОНГ ФЕНГ", "DONGFENG"},
	{"ДУНФЭН", "DONGFENG"},
	{"ДУНФЫН", "DONGFENG"},
	{"ИОНИКС", "EONYX"},
	{"ЭОНИКС", "EONYX"},
	{"ЭВОЛЮТ", "EVOLUTE"},
	{"ЭВОЛЮТЕ", "EVOLUTE"},
	{"ЭКСИД", "EXEED"},
	{"ИКСИД", "EXEED"},
	{"ЭКЗИД", "EXEED"},
	{"ЭКСЛАНТИКС", "EXLANTIX"},
	{"ЭКСЛАНИКС", "EXLANTIX"},
	{"ФАВ", "FAW"},
	{"ФОТОН", "FOTON"},
	{"ГАК", "GAC"},
	{"ДЖИЭЙСИ", "GAC"},
	{"ТРАМПЧИ", "GAC TRUMPCHI"},
	{"ДЖИЛИ", "GEELY"},
	{"ДЖИЛЛИ", "GEELY"},
	{"ГИЛИ", "GEELY"},
	{"ГРЕЙТ ВОЛЛ", "GREAT WALL"},
	{"ГРЕЙТ ВОЛ", "GREAT WALL"},
	{"ГРЭЙТ ВОЛЛ", "GREAT WALL"},
	{"ХАВАЛ", "HAVAL"},
	{"ХАВЕЙЛ", "HAVAL"},
	{"ХАВЭЙЛ", "HAVAL"},
	{"ХАВЕЛ", "HAVAL"},
	{"ХОНКИ", "HONGQI"},
	{"ХУНЦИ", "HONGQI"},
	{"ХОНГКИ", "HONGQI"},
	{"ДЖАК", "JAC"},
	{"ДЖЕЙКУ", "JAECOO"},
	{"ДЖЕЙКОО", "JAECOO"},
	{"ДЖЕЙКО", "JAECOO"},
	{"ДЖАЕКУ", "JAECOO"},
	{"ДЖЭКУ", "JAECOO"},
	{"ЖАЕКУ", "JAECOO"},
	{"ДЖАЕКО", "JAECOO"},
	{"ДЖЕЛАНД", "JELAND"},
	{"ЖЕЛАНД", "JELAND"},
	{"ДЖЕТТА", "JETTA"},
	{"ДЖЕТУР", "JETOUR"},
	{"ДЖЕТОУР", "JETOUR"},
	{"ЖЕТУР", "JETOUR"},
	{"КАЙИ", "KAIYI"},
	{"КАИИ", "KAIYI"},
	{"КАЙИЙ", "KAIYI"},
	{"НЬЮСТАР", "KNEWSTAR"},
	{"НЮСТАР", "KNEWSTAR"},
	{"КНЬЮСТАР", "KNEWSTAR"},
	{"ЛИФАН", "LIFAN"},
	{"ЛИВАН", "LIVAN"},
	{"ЛИСЯН", "LIXIANG"},
	{"ЛИСЯНГ", "LIXIANG"},
	{"ЛИ АВТО", "LIXIANG"},
	{"ЛИКСИАНГ", "LIXIANG"},
	{"ЛИАВТО", "LIXIANG"},
	{"ЛИНК ЭНД КО", "LYNK & CO"},
	{"ЛИНК И КО", "LYNK & CO"},
	{"ЭМ ДЖИ", "MG"},
	{"ЭМДЖИ", "MG"},
	{"ЭМ ХИРО", "M-HERO"},
	{"НОРДКРОСС", "NORDCROSS"},
	{"ОМОДА", "OMODA"},
	{"ОРА", "ORA"},
	{"РОКС", "ROX"},
	{"СЕРЕС", "SERES"},
	{"СЕРИС", "SERES"},
	{"СКАЙВЕЛЛ", "SKYWELL"},
	{"СКАЙВЕЛ", "SKYWELL"},
	{"СОУИСТ", "SOUEAST"},
	{"СВМ", "SWM"},
	{"ЭСВЭМ", "SWM"},
	{"ТАНК", "TANK"},
	{"ТЕНЕТ", "TENET"},
	{"ВОЯХ", "VOYAH"},
	{"ВОЯЖ", "VOYAH"},
	{"ВОЯХА", "VOYAH"},
	{"ВЕЙ", "WEY"},
	{"ВЭЙ", "WEY"},
	{"ИКСАЙТ", "XCITE"},
	{"ЭКСАЙТ", "XCITE"},
	{"СЯОМИ", "XIAOMI"},
	{"ШАОМИ", "XIAOMI"},
	{"ЗИКР", "ZEEKR"},
	{"ЗИИКР", "ZEEKR"},
	{"ЗИКЕР", "ZEEKR"},
	{"ЗОТИ", "ZOTYE"},
	{"ЗОТАЙ", "ZOTYE"},
	{"ЛАДА", "LADA"},
	{"ВАЗ", "LADA"},
	{"МОСКВИЧЬ", "МОСКВИЧ"},
	{"АУРУС", "AURUS"},
	{"СОЛЯРИС", "SOLARIS"},
	{"СОЛЛЕРС", "SOLLERS"},
	{"АМБЕР АВТО", "АМБЕРАВТО"},
	{"АМБЕР", "АМБЕРАВТО"},

	// Models
	{"МДХ", "MDX"},
	{"РДХ", "RDX"},
	{"ТЛХ", "TLX"},
	{"ДЖУЛЬЕТТА", "GIULIETTA"},
	{"ДЖУЛИЯ", "GIULIA"},
	{"СТЕЛЬВИО", "STELVIO"},
	{"ВАНТЭДЖ", "VANTAGE"},
	{"ВАНТАЖ", "VANTAGE"},
	{"КУ3", "Q3"},
	{"КУ5", "Q5"},
	{"КУ7", "Q7"},
	{"КУ8", "Q8"},
	{"ОЛРОУД", "ALLROAD"},
	{"ЭТРОН", "E-TRON"},
	{"Е-ТРОН", "E-TRON"},
	{"БИДЖ40", "BJ40"},
	{"БИДЖ60", "BJ60"},
	{"БЕСТЮН Т77", "BESTUNE T77"},
	{"БЕСТЮН Т99", "BESTUNE T99"},
	{"БЕСТЮН Т55", "BESTUNE T55"},
	{"БЕСТЮН Б70", "BESTUNE B70"},
	{"Х1", "X1"},
	{"Х2", "X2"},
	{"Х3", "X3"},
	{"Х4", "X4"},
	{"Х5", "X5"},
	{"Х6", "X6"},
	{"Х7", "X7"},
	{"ИКС1", "X1"},
	{"ИКС3", "X3"},
	{"ИКС5", "X5"},
	{"ИКС6", "X6"},
	{"ИКС7", "X7"},
	{"ТРОЙКА", "3 SERIES"},
	{"ПЯТЁРКА", "5 SERIES"},
	{"ПЯТЕРКА", "5 SERIES"},
	{"СЕМЁРКА", "7 SERIES"},
	{"СЕМЕРКА", "7 SERIES"},
	{"ХАН", "HAN"},
	{"ТАНЬ", "TANG"},
	{"СОНГ", "SONG"},
	{"СИЯЛ", "SEAL"},
	{"ДЕЛЬФИН", "DOLPHIN"},
	{"ЮАНЬ", "YUAN"},
	{"ЯНВАН", "YANGWANG"},
	{"ЭСКАЛЕЙД", "ESCALADE"},
	{"ЭСКАЛЭЙД", "ESCALADE"},
	{"АЛЬСВИН", "ALSVIN"},
	{"ЭЛСВИН", "ALSVIN"},
	{"ХАНТЕР", "HUNTER"},
	{"ХАНТЕР ПЛЮС", "HUNTER PLUS"},
	{"ЭАДО", "EADO"},
	{"ЭАДО ПЛЮС", "EADO PLUS"},
	{"УНИ-К", "UNI-K"},
	{"ЮНИК", "UNI-K"},
	{"УНИ К", "UNI-K"},
	{"УНИ-В", "UNI-V"},
	{"УНИ В", "UNI-V"},
	{"ЮНИВ", "UNI-V"},
	{"УНИ-С", "UNI-S"},
	{"УНИ С", "UNI-S"},
	{"ЮНИС", "UNI-S"},
	{"УНИ-Т", "UNI-T"},
	{"УНИ Т", "UNI-T"},
	{"ЮНИТ", "UNI-T"},
	{"ТИГГО", "TIGGO"},
	{"АРРИЗО", "ARRIZO"},
	{"АРИЗО", "ARRIZO"},
	{"КРУЗ", "CRUZE"},
	{"АВЕО", "AVEO"},
	{"ЛАЧЕТТИ", "LACETTI"},
	{"КАПТИВА", "CAPTIVA"},
	{"ОРЛАНДО", "ORLANDO"},
	{"МАЛИБУ", "MALIBU"},
	{"ТАХО", "TAHOE"},
	{"ТРЕЙЛБЛЕЙЗЕР", "TRAILBLAZER"},
	{"ТРЭЙЛБЛЕЙЗЕР", "TRAILBLAZER"},
	{"СПАРК", "SPARK"},
	{"КОБАЛЬТ", "COBALT"},
	{"ЭПИКА", "EPICA"},
	{"КАМАРО", "CAMARO"},
	{"ТРЕВИС", "TRAVERSE"},
	{"ВОЯДЖЕР", "VOYAGER"},
	{"ПАЦИФИКА", "PACIFICA"},
	{"СЕБРИНГ", "SEBRING"},
	{"БЕРЛИНГО", "BERLINGO"},
	{"НЕКСИЯ", "NEXIA"},
	{"МАТИЗ", "MATIZ"},
	{"ДЖЕНТРА", "GENTRA"},
	{"ЛАНОС", "LANOS"},
	{"НУБИРА", "NUBIRA"},
	{"ЛЕГАНЗА", "LEGANZA"},
	{"ЭСПЕРО", "ESPERO"},
	{"КАЛИБР", "CALIBER"},
	{"ЧАРДЖЕР", "CHARGER"},
	{"ЧЕЛЛЕНДЖЕР", "CHALLENGER"},
	{"ДЮРАНГО", "DURANGO"},
	{"КАРАВАН", "CARAVAN"},
	{"ШАЙН МАКС", "SHINE MAX"},
	{"МЕЙДЖ", "MAGE"},
	{"ХЬЮДЖ", "HUGE"},
	{"ТИЭКСЭЛЬ", "TXL"},
	{"ПУНТО", "PUNTO"},
	{"ЛИНЕА", "LINEA"},
	{"БРАВО", "BRAVO"},
	{"АЛЬБЕА", "ALBEA"},
	{"ДОБЛО", "DOBLO"},
	{"ДУКАТО", "DUCATO"},
	{"ПАНДА", "PANDA"},
	{"ФОКУС", "FOCUS"},
	{"МОНДЕО", "MONDEO"},
	{"КУГА", "KUGA"},
	{"ФИЕСТА", "FIESTA"},
	{"ЭКСПЛОРЕР", "EXPLORER"},
	{"РЕЙНДЖЕР", "RANGER"},
	{"МУСТАНГ", "MUSTANG"},
	{"БРОНКО", "BRONCO"},
	{"МАВЕРИК", "MAVERICK"},
	{"ГАЛАКСИ", "GALAXY"},
	{"ФЬЮЖН", "FUSION"},
	{"ТРАНЗИТ", "TRANSIT"},
	{"ЭКОСПОРТ", "ECOSPORT"},
	{"ЭДЖ", "EDGE"},
	{"ЭМПАУ", "EMPOW"},
	{"ЭМПОВ", "EMPOW"},
	{"МОНЖАРО", "MONJARO"},
	{"МАНЖАРО", "MONJARO"},
	{"МОНДЖАРО", "MONJARO"},
	{"АТЛАС", "ATLAS"},
	{"АТЛАС ПРО", "ATLAS PRO"},
	{"ОКАВАНГО", "OKAVANGO"},
	{"ПРЕФЕЙС", "PREFACE"},
	{"ПРИФЕЙС", "PREFACE"},
	{"СИТИРЭЙ", "CITYRAY"},
	{"СИТИРЕЙ", "CITYRAY"},
	{"КУЛРЕЙ", "COOLRAY"},
	{"КУЛРЭЙ", "COOLRAY"},
	{"ТУГЕЛЛА", "TUGELLA"},
	{"ТУГЕЛА", "TUGELLA"},
	{"ЭМГРАНД", "EMGRAND"},
	{"ХОВЕР", "HOVER"},
	{"ВИНГЛ", "WINGLE"},
	{"ДИРЬ", "DEER"},
	{"СЕЙФ", "SAFE"},
	{"ПЕГАСУС", "PEGASUS"},
	{"ДАРГО", "DARGO"},
	{"ДЖОЛИОН", "JOLION"},
	{"ДЖУЛЬОН", "JOLION"},
	{"ЖОЛИОН", "JOLION"},
	{"ПОЕР", "POER"},
	{"ЦИВИК", "CIVIC"},
	{"АККОРД", "ACCORD"},
	{"СРВ", "CR-V"},
	{"СР-В", "CR-V"},
	{"ПИЛОТ", "PILOT"},
	{"ДЖАЗ", "JAZZ"},
	{"ФИТ", "FIT"},
	{"СТРИМ", "STREAM"},
	{"КРЕТА", "CRETA"},
	{"ТУССАН", "TUCSON"},
	{"ТУСАН", "TUCSON"},
	{"ТУКСОН", "TUCSON"},
	{"ТУСОН", "TUCSON"},
	{"САНТА ФЕ", "SANTA FE"},
	{"САНТАФЕ", "SANTA FE"},
	{"ПАЛИСАД", "PALISADE"},
	{"ЭЛАНТРА", "ELANTRA"},
	{"СОНАТА", "SONATA"},
	{"АКЦЕНТ", "ACCENT"},
	{"КОНА", "KONA"},
	{"СТАРЕКС", "STARIA"},
	{"СТАРИЯ", "STARIA"},
	{"ГЕТЦ", "GETZ"},
	{"ГЕТЗ", "GETZ"},
	{"ПОРТЕР", "PORTER"},
	{"ВЕРНА", "VERNA"},
	{"МАТРИКС", "MATRIX"},
	{"ТРЭДЖЕТ", "TRAJET"},
	{"ТРАДЖЕТ", "TRAJET"},
	{"ГРАНДЁР", "GRANDEUR"},
	{"ГРАНДЕР", "GRANDEUR"},
	{"АЙ30", "I30"},
	{"АЙ40", "I40"},
	{"ИОНИК", "IONIQ"},
	{"ФХ", "FX"},
	{"ДЖЕЙ6", "J6"},
	{"ДЖЕЙ7", "J7"},
	{"ДЖЕЙ8", "J8"},
	{"РЭНГЛЕР", "WRANGLER"},
	{"РЕНГЛЕР", "WRANGLER"},
	{"ВРАНГЛЕР", "WRANGLER"},
	{"ГРАНД ЧЕРОКИ", "GRAND CHEROKEE"},
	{"ГРАНДЧЕРОКИ", "GRAND CHEROKEE"},
	{"ЧЕРОКИ", "CHEROKEE"},
	{"КОМПАС", "COMPASS"},
	{"КОММАНДЕР", "COMMANDER"},
	{"РЕНЕГАД", "RENEGADE"},
	{"ДАШИНГ", "DASHING"},
	{"ДЭШИНГ", "DASHING"},
	{"КУНЛУН", "KUNLUN"},
	{"КОРАНДО", "KORANDO"},
	{"РЕКСТОН", "REXTON"},
	{"ТОРРЕС", "TORRES"},
	{"ТОРЕС", "TORRES"},
	{"АКТИОН", "ACTYON"},
	{"КАЙРОН", "KYRON"},
	{"МУССО", "MUSSO"},
	{"ТИВОЛИ", "TIVOLI"},
	{"СТАВИК", "STAVIC"},
	{"РОДИУС", "RODIUS"},
	{"РИО", "RIO"},
	{"СИИД", "CEED"},
	{"СИД", "CEED"},
	{"ЦЕРАТО", "CERATO"},
	{"СЕРАТО", "CERATO"},
	{"СПОРТЕЙДЖ", "SPORTAGE"},
	{"СПОРТЭЙДЖ", "SPORTAGE"},
	{"СПОРТАЖ", "SPORTAGE"},
	{"СОРЕНТО", "SORENTO"},
	{"ОПТИМА", "OPTIMA"},
	{"СЕЛТОС", "SELTOS"},
	{"СТОНИК", "STONIC"},
	{"КАРЕНС", "CARENS"},
	{"КАРНИВАЛ", "CARNIVAL"},
	{"МОХАВ", "MOHAVE"},
	{"ПИКАНТО", "PICANTO"},
	{"СТИНГЕР", "STINGER"},
	{"НИРО", "NIRO"},
	{"СОУЛ", "SOUL"},
	{"СПЕКТРА", "SPECTRA"},
	{"МАДЖЕНТИС", "MAGENTIS"},
	{"ВЕНГА", "VENGA"},
	{"ГРАНТА", "GRANTA"},
	{"ВЕСТА", "VESTA"},
	{"НИВА", "NIVA"},
	{"ЛАРГУС", "LARGUS"},
	{"ИСКРА", "ISKRA"},
	{"АУРА", "AURA"},
	{"ПРИОРА", "PRIORA"},
	{"КАЛИНА", "KALINA"},
	{"САМАРА", "SAMARA"},
	{"АЗИМУТ", "AZIMUT"},
	{"РЕЙНДЖРОВЕР", "RANGE ROVER"},
	{"РЭНДЖРОВЕР", "RANGE ROVER"},
	{"РЕЙНДЖ РОВЕР", "RANGE ROVER"},
	{"РЭНДЖ РОВЕР", "RANGE ROVER"},
	{"ДИСКАВЕРИ", "DISCOVERY"},
	{"ДЕФЕНДЕР", "DEFENDER"},
	{"ФРИЛЕНДЕР", "FREELANDER"},
	{"ЭВОК", "EVOQUE"},
	{"ВЕЛАР", "VELAR"},
	{"ЛЕКСУС РХ", "LEXUS RX"},
	{"ЛЕКСУС НХ", "LEXUS NX"},
	{"ЛЕКСУС ЛХ", "LEXUS LX"},
	{"СОЛАНО", "SOLANO"},
	{"БРИЗ", "BREEZ"},
	{"СМАЙЛИ", "SMILY"},
	{"ДЕМИО", "DEMIO"},
	{"АТЕНЗА", "ATENZA"},
	{"АКСЕЛА", "AXELA"},
	{"ТРИБЬЮТ", "TRIBUTE"},
	{"ГЕЛИК", "G-CLASS"},
	{"ГЕЛЕНДВАГЕН", "G-CLASS"},
	{"ГЕЛЕНД", "G-CLASS"},
	{"ГЕЛЕНТВАГЕН", "G-CLASS"},
	{"МАЙБАХ", "MAYBACH"},
	{"ВИТО", "VITO"},
	{"ВИАНО", "VIANO"},
	{"СПРИНТЕР", "SPRINTER"},
	{"КУПЕР", "COOPER"},
	{"КАНТРИМЕН", "COUNTRYMAN"},
	{"КАНТРИМЭН", "COUNTRYMAN"},
	{"ПЕЙСМЕН", "PACEMAN"},
	{"КЛАБМЕН", "CLUBMAN"},
	{"ЛАНСЕР", "LANCER"},
	{"АУТЛЕНДЕР", "OUTLANDER"},
	{"ПАДЖЕРО", "PAJERO"},
	{"ПАДЖЕРО СПОРТ", "PAJERO SPORT"},
	{"ЭКЛИПС КРОСС", "ECLIPSE CROSS"},
	{"ЭКЛИПС", "ECLIPSE"},
	{"КОЛЬТ", "COLT"},
	{"ГАЛАНТ", "GALANT"},
	{"КАРИЗМА", "CARISMA"},
	{"ГРАНДИС", "GRANDIS"},
	{"ДЕЛИКА", "DELICA"},
	{"Л200", "L200"},
	{"ЭЛ200", "L200"},
	{"КАШКАЙ", "QASHQAI"},
	{"КАШКАИ", "QASHQAI"},
	{"ИКСТРЕЙЛ", "X-TRAIL"},
	{"Х-ТРЕЙЛ", "X-TRAIL"},
	{"ПАТФАЙНДЕР", "PATHFINDER"},
	{"МУРАНО", "MURANO"},
	{"ЖУК", "JUKE"},
	{"НАВАРА", "NAVARA"},
	{"ТИИДА", "TIIDA"},
	{"АЛЬМЕРА", "ALMERA"},
	{"НОУТ", "NOTE"},
	{"ПРИМЕРА", "PRIMERA"},
	{"МАКСИМА", "MAXIMA"},
	{"ТЕРРАНО", "TERRANO"},
	{"ПАТРОЛ", "PATROL"},
	{"ТЕАНА", "TEANA"},
	{"ЛИФ", "LEAF"},
	{"СЕНТРА", "SENTRA"},
	{"МИКРА", "MICRA"},
	{"МАРЧ", "MARCH"},
	{"АСТРА", "ASTRA"},
	{"КОРСА", "CORSA"},
	{"ИНСИГНИЯ", "INSIGNIA"},
	{"МОККА", "MOKKA"},
	{"ЗАФИРА", "ZAFIRA"},
	{"МЕРИВА", "MERIVA"},
	{"ВЕКТРА", "VECTRA"},
	{"АНТАРА", "ANTARA"},
	{"ФРОНТЕРА", "FRONTERA"},
	{"ОМЕГА", "OMEGA"},
	{"ВИВАРО", "VIVARO"},
	{"КАДЕТ", "KADETT"},
	{"ПАРТНЕР", "PARTNER"},
	{"БОКСЕР", "BOXER"},
	{"ЭКСПЕРТ", "EXPERT"},
	{"КАЙЕН", "CAYENNE"},
	{"КАЕН", "CAYENNE"},
	{"КАЙЕНН", "CAYENNE"},
	{"ПАНАМЕРА", "PANAMERA"},
	{"МАКАН", "MACAN"},
	{"ТАЙКАН", "TAYCAN"},
	{"КАРРЕРА", "CARRERA"},
	{"БОКСТЕР", "BOXSTER"},
	{"ДАСТЕР", "DUSTER"},
	{"ЛОГАН", "LOGAN"},
	{"САНДЕРО", "SANDERO"},
	{"КАПТУР", "KAPTUR"},
	{"АРКАНА", "ARKANA"},
	{"КОЛЕОС", "KOLEOS"},
	{"МЕГАН", "MEGANE"},
	{"ФЛЮЕНС", "FLUENCE"},
	{"СИМБОЛ", "SYMBOL"},
	{"КАНГУ", "KANGOO"},
	{"МАСТЕР", "MASTER"},
	{"ЛАГУНА", "LAGUNA"},
	{"СЦЕНИК", "SCENIC"},
	{"ЛАТИТЮД", "LATITUDE"},
	{"АДАМАС", "ADAMAS"},
	{"ОКТАВИЯ", "OCTAVIA"},
	{"РАПИД", "RAPID"},
	{"КОДИАК", "KODIAQ"},
	{"КАРОК", "KAROQ"},
	{"СУПЕРБ", "SUPERB"},
	{"ФАБИЯ", "FABIA"},
	{"ЙЕ", "YETI"},
	{"ЙЕТИ", "YETI"},
	{"РУМСТЕР", "ROOMSTER"},
	{"КАМИК", "KAMIQ"},
	{"СКАЛА", "SCALA"},
	{"АРГО", "ARGO"},
	{"АТЛАНТ", "ATLANT"},
	{"ФОРЕСТЕР", "FORESTER"},
	{"АУТБЭК", "OUTBACK"},
	{"АУТБЕК", "OUTBACK"},
	{"ИМПРЕЗА", "IMPREZA"},
	{"ЛЕГАСИ", "LEGACY"},
	{"ТРИБЕКА", "TRIBECA"},
	{"ЛЕВОРГ", "LEVORG"},
	{"ВИТАРА", "VITARA"},
	{"ГРАНД ВИТАРА", "GRAND VITARA"},
	{"ГРАНДВИТАРА", "GRAND VITARA"},
	{"ДЖИМНИ", "JIMNY"},
	{"СВИФТ", "SWIFT"},
	{"ЛИАНА", "LIANA"},
	{"СПЛЭШ", "SPLASH"},
	{"БАЛЕНО", "BALENO"},
	{"ИГНИС", "IGNIS"},
	{"ЭСКУДО", "ESCUDO"},
	{"ХАСТЛЕР", "HUSTLER"},
	{"Т4", "T4"},
	{"Т7", "T7"},
	{"Т8", "T8"},
	{"Т9", "T9"},
	{"МОДЕЛ 3", "MODEL 3"},
	{"МОДЕЛ С", "MODEL S"},
	{"МОДЕЛ У", "MODEL Y"},
	{"МОДЕЛ Х", "MODEL X"},
	{"КАМРИ", "CAMRY"},
	{"КОРОЛЛА", "COROLLA"},
	{"КОРАЛЛА", "COROLLA"},
	{"РАВ4", "RAV4"},
	{"РАВ 4", "RAV4"},
	{"ЛЕНД КРУЗЕР", "LAND CRUISER"},
	{"ЛЭНД КРУЗЕР", "LAND CRUISER"},
	{"ЛАНДКРУЗЕР", "LAND CRUISER"},
	{"ПРАДО", "PRADO"},
	{"ХАЙЛЕНДЕР", "HIGHLANDER"},
	{"ХАЙЛЭНДЕР", "HIGHLANDER"},
	{"ФОРТУНЕР", "FORTUNER"},
	{"ХАЙЛЮКС", "HILUX"},
	{"ХАЙЭЙС", "HIACE"},
	{"АВЕНСИС", "AVENSIS"},
	{"АУРИС", "AURIS"},
	{"ПРИУС", "PRIUS"},
	{"ЯРИС", "YARIS"},
	{"ВЕРСО", "VERSO"},
	{"АЛЬФАРД", "ALPHARD"},
	{"СУУРРА", "SUPRA"},
	{"СУПРА", "SUPRA"},
	{"ВИСТА", "VISTA"},
	{"ВЕНЗА", "VENZA"},
	{"СЕЛИКА", "CELICA"},
	{"ХАРРИЕР", "HARRIER"},
	{"МАРКХ", "MARK X"},
	{"ТУНДРА", "TUNDRA"},
	{"СЕКВОЙЯ", "SEQUOIA"},
	{"ЭФ ДЖЕ КРУЗЕР", "FJ CRUISER"},
	{"ТИГУАН", "TIGUAN"},
	{"ТУАРЕГ", "TOUAREG"},
	{"ПОЛО", "POLO"},
	{"ГОЛЬФ", "GOLF"},
	{"ПАССАТ", "PASSAT"},
	{"АРТЕОН", "ARTEON"},
	{"ТАЙРОК", "TAYROC"},
	{"ТЕРАМОНТ", "TERAMONT"},
	{"ТРАНСПОРТЕР", "TRANSPORTER"},
	{"КЭДДИ", "CADDY"},
	{"КАРАВЕЛЛА", "CARAVELLE"},
	{"МУЛЬТИВЭН", "MULTIVAN"},
	{"АМАРОК", "AMAROK"},
	{"БОРА", "BORA"},
	{"ТУРАН", "TOURAN"},
	{"ШАРАН", "SHARAN"},
	{"ЭОС", "EOS"},
	{"СИРОККО", "SCIROCCO"},
	{"КРАФТЕР", "CRAFTER"},
	{"ТАЙГУН", "TAIGUN"},
	{"ФРИИ", "FREE"},
	{"ДРИМ", "DREAM"},
	{"ПЭШН", "PASSION"},
	{"ПЭШЕН", "PASSION"},
	{"Х-КРОСС", "X-CROSS"},
	{"ИКСКРОСС", "X-CROSS"},
	{"АЙ ПРО", "I-PRO"},
	{"АЙ ДЖОЙ", "I-JOY"},
	{"АЙ СКАЙ", "I-SKY"},
	{"АЙ ДЖЕТ", "I-JET"},
	{"ПАТРИОТ", "PATRIOT"},
	{"БУХАНКА", "БУХАНКА"},
	{"ТУНЛАНД", "TUNLAND"},
	{"ИБИЦА", "IBIZA"},
	{"ЛЕОН", "LEON"},
	{"ТОЛЕДО", "TOLEDO"},
	{"АЛЬТЕА", "ALTEA"},
	{"АТЕКА", "ATECA"},
	{"АРРОНА", "ARONA"},
	{"АЛХАМБРА", "ALHAMBRA"},
	{"К5", "K5"},
	{"К8", "K8"},
	{"К9", "K9"},
	{"С5", "C5"},
	{"С7", "C7"},
	{"НАВИГАТОР", "NAVIGATOR"},
	{"АВИАТОР", "AVIATOR"},
	{"КОНТИНЕНТАЛЬ", "CONTINENTAL"},
	{"БЕНТАЙГА", "BENTAYGA"},
	{"ФЛАИНГ СПУР", "FLYING SPUR"},
	{"ФАНТОМ", "PHANTOM"},
	{"ГОСТ", "GHOST"},
	{"ВРАЙТ", "WRAITH"},
	{"КАЛЛИНАН", "CULLINAN"},
	{"КУЛИНАН", "CULLINAN"},
	{"КВАТРОПОРТЕ", "QUATTROPORTE"},
	{"ГИБЛИ", "GHIBLI"},
	{"ЛЕВАНТЕ", "LEVANTE"},
	{"ГРЕКАЛЕ", "GRECALE"},
	{"ПОРТОФИНО", "PORTOFINO"},
	{"ПУРОСАНГВЕ", "PUROSANGUE"},
	{"УРУС", "URUS"},
	{"ХУРАКАН", "HURACAN"},
	{"РЕВУЭЛТО", "REVUELTO"},
	{"АВЕНТАДОР", "AVENTADOR"},
	{"ГАЛЬЯРДО", "GALLARDO"},
}
